//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codita
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string EmailId { get; set; }
        public string PhoneNumber { get; set; }
        public string UserAddress { get; set; }
        public string Gender { get; set; }
        public string UserId { get; set; }
        public string UserPassword { get; set; }
        public string ImageUrl { get; set; }

    }
}
